apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: classroom-booking
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: messaging
type: Opaque
# Values are base64-encoded: echo -n 'guest' | base64 → Z3Vlc3Q=
# Change these in production!
data:
  username: Z3Vlc3Q=   # guest
  password: Z3Vlc3Q=   # guest

