package com.classroom.common.dto;

import com.classroom.common.enums.BookingStatus;
import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Payload published to the {@code booking.requested} RabbitMQ queue and also
 * used as the inbound REST request body on {@code POST /bookings}.
 *
 * <p>The {@code bookingId} is generated by the booking service (UUID v4) before
 * the event is published; it is {@code null} when the DTO arrives from the client.
 *
 * <p>Jackson serialisation notes:
 * <ul>
 *   <li>{@code date} → {@code "yyyy-MM-dd"}</li>
 *   <li>{@code timeSlot.startTime} / {@code endTime} → {@code "HH:mm"}</li>
 * </ul>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class BookingRequest {

    /**
     * Unique identifier assigned by the booking service.
     * {@code null} on initial REST submission; populated before queue publish.
     */
    private String bookingId;

    /**
     * Identifier of the classroom to be booked (e.g. {@code "CR-101"}).
     */
    @NotBlank(message = "classroomId must not be blank")
    private String classroomId;

    /**
     * The date on which the classroom is being requested.
     * Must not be in the past.
     */
    @NotNull(message = "date must not be null")
    @FutureOrPresent(message = "date must be today or a future date")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate date;

    /**
     * Requested time slot.  Validated for [start < end] by
     * {@link com.classroom.common.util.TimeSlotUtils#isValid(TimeSlot)}.
     */
    @NotNull(message = "timeSlot must not be null")
    @Valid
    private TimeSlot timeSlot;

    /**
     * E-mail address of the person who submitted the booking.
     * Used by the notification service to send confirmations/rejections.
     */
    @NotBlank(message = "requestedBy must not be blank")
    @Email(message = "requestedBy must be a valid e-mail address")
    private String requestedBy;

    /**
     * Current lifecycle status of this booking.
     * Defaults to {@link BookingStatus#PENDING} when first created.
     */
    @Builder.Default
    private BookingStatus status = BookingStatus.PENDING;
}

